# MULTIPLE LINEAR REGRESSION USING SKLEARN LIBRARY:

### STEP 1:Importing the necessary libraries for the dataset.Also importing the diabetes dataset from sklearn.

In [69]:
import numpy as np
from sklearn.datasets import load_diabetes

In [70]:
X,y=load_diabetes(return_X_y=True)

In [71]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [72]:
X.shape

(442, 10)

In [73]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [74]:
y.shape

(442,)

### STEP2:Importing train test split and splitting the data into training and testing dataset.

In [75]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [76]:
print(f'{X_train.shape}<- is the training dataset shape and {X_test.shape}<- is the test data')

(353, 10)<- is the training dataset shape and (89, 10)<- is the test data


In [77]:
print(f'{y_train.shape}<- is the y training dataset shape and {y_test.shape}<- is the test data')

(353,)<- is the y training dataset shape and (89,)<- is the test data


### STEP 3:Importing the Linear Regression module from sklearn to implement it on the training dataset.

In [78]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [79]:
#fitting the model into the linear regression model.
lr.fit(X_train,y_train)

LinearRegression()

In [80]:
#finding the value of y prediction values.
y_pred=lr.predict(X_test)

In [81]:
y_pred

array([247.20145833, 172.85994688,  76.8458742 , 193.00059702,
       100.28696634, 168.37456091,  81.66639595, 218.82803362,
       196.55728665, 184.67533075, 177.90994595, 153.53366721,
       176.99111659, 229.48110415,  57.08476304, 196.58324018,
       255.58929965,  85.85605139, 202.0486218 ,  69.22989475,
       169.1304953 , 193.37382886, 164.42997134, 155.98284129,
       159.85889722, 103.83787347,  98.99302305, 176.26522999,
       165.45962337, 169.52257328, 153.84090734,  83.50739012,
       137.50959329, 145.84520909, 108.60605477, 148.85733126,
       134.8360016 , 237.90585502, 260.53340411, 126.15200694,
       217.58301627, 228.76174393, 163.00905582, 110.13793169,
       121.71002437, 148.68182957, 202.90692126, 139.91700144,
       143.84493373,  93.54174033,  87.53441565,  77.05966895,
       103.00000769,  97.03831966, 148.52059932, 131.67009586,
        32.11306683,  75.45837207,  68.0720316 , 253.5080215 ,
       113.69571782, 204.10508503, 191.18020679, 207.91

### STEP 4:Importing r2 score from sklearn 

In [82]:
from sklearn.metrics import r2_score

In [83]:
r2_score(y_test,y_pred)

0.5505453765626078

### STEP 5:Now we obtain the values for the coefficient that is the value of co efficients and the intercept is the value for offset.

In [84]:
for d, coef in enumerate(lr.coef_):
    print(f'The coefficient beta{d} is: {coef}')


The coefficient beta0 is: -17.23220816374574
The coefficient beta1 is: -225.20253652191286
The coefficient beta2 is: 465.9861731154056
The coefficient beta3 is: 359.8697513713534
The coefficient beta4 is: -752.0345792657871
The coefficient beta5 is: 513.2418483109903
The coefficient beta6 is: 75.51984952578034
The coefficient beta7 is: 133.4823173066623
The coefficient beta8 is: 779.0967630578413
The coefficient beta9 is: 23.558170458006956


In [85]:
lr.intercept_

151.4989268933548

# MAKING A MANUAL MULTIPLE LINEAR REGRESSION CLASS


### STEP 1:Formation of class that contains functions called fit and predict and two values coeffficient and intercept.

In [86]:
class mlr:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self, X_train, y_train):
        import numpy as np
        X_train = np.insert(X_train, 0, 1, axis=1)
        # Calculation of coefficients
        beta_values = np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = beta_values[0]
        self.coef_ = beta_values[1:]
        
    def predict(self, X_test):
        import numpy as np
        X_test = np.insert(X_test, 0, 1, axis=1)
        predictions = np.dot(X_test, np.concatenate(([self.intercept_], self.coef_)))
        return predictions

    

### STEP 2:Fitting the same training and testing dataset to our multiple regression class or model

In [87]:
multiple=mlr()

In [88]:
multiple.fit(X_train,y_train)

In [89]:
multiple.predict(X_test)

array([247.20145833, 172.85994688,  76.8458742 , 193.00059702,
       100.28696634, 168.37456091,  81.66639595, 218.82803362,
       196.55728665, 184.67533075, 177.90994595, 153.53366721,
       176.99111659, 229.48110415,  57.08476304, 196.58324018,
       255.58929965,  85.85605139, 202.0486218 ,  69.22989475,
       169.1304953 , 193.37382886, 164.42997134, 155.98284129,
       159.85889722, 103.83787347,  98.99302305, 176.26522999,
       165.45962337, 169.52257328, 153.84090734,  83.50739012,
       137.50959329, 145.84520909, 108.60605477, 148.85733126,
       134.8360016 , 237.90585502, 260.53340411, 126.15200694,
       217.58301627, 228.76174393, 163.00905582, 110.13793169,
       121.71002437, 148.68182957, 202.90692126, 139.91700144,
       143.84493373,  93.54174033,  87.53441565,  77.05966895,
       103.00000769,  97.03831966, 148.52059932, 131.67009586,
        32.11306683,  75.45837207,  68.0720316 , 253.5080215 ,
       113.69571782, 204.10508503, 191.18020679, 207.91

### STEP 3:Calculating the value of the intercept and the coefficients of our manual model

In [90]:
for d, coef in enumerate(lr.coef_):
    print(f'The coefficient beta{d} is: {coef}')

The coefficient beta0 is: -17.23220816374574
The coefficient beta1 is: -225.20253652191286
The coefficient beta2 is: 465.9861731154056
The coefficient beta3 is: 359.8697513713534
The coefficient beta4 is: -752.0345792657871
The coefficient beta5 is: 513.2418483109903
The coefficient beta6 is: 75.51984952578034
The coefficient beta7 is: 133.4823173066623
The coefficient beta8 is: 779.0967630578413
The coefficient beta9 is: 23.558170458006956


In [91]:
multiple.intercept_
    

151.4989268933548

# CONCLUSION:
Hence we conclude from implementing our own model for multiple linear regression and the linear regression from sklearn library that the vakues of the offset i.e. intercept and the value of the coefficients are exactly the same.
We have used the OLS(Ordinary Least Square)Method to derive the formulas and it is clearly derivable that the sklearn library uses the same for the linear regression model.